# -*- coding: utf-8 -*-
"""compra-acoes-para-carteira.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1x6_vlvGfhPEyD8ao8gHOxDi-YgWJeHLk
"""

import pandas as pd
import numpy as np
import yfinance as yf

compras = {'VALE3.SA':200,'AAPL34.SA':500,
           'COCA34.SA':300,'WEGE3.SA':350,
           'PETR4.SA':400,
           'BPAC11.SA':100,
           'SMAL11.SA':100,
           'TAEE11.SA' :200
           }

list(compras.keys())
sum(compras.values())

inicio = '2021-01-01'
fim = '2023-01-01'

precos = yf.download(list(compras.keys()), start = inicio, end = fim, progress=False)
primeiro = precos.iloc[0]

compras_df = pd.Series(compras, index=list(compras.keys()))
qtd_acoes = round(compras_df/primeiro[0])
qtd_acoes = round(compras_df/primeiro['Close'])
qtd_acoes

PL = precos['Close'] * qtd_acoes
PL['PL TOTAL'] = PL.sum(axis=1)
PL.head()

ibov = yf.download('^BVSP', start = inicio, end = fim, progress=False)['Close']

pd.DataFrame(ibov)

consolido = pd.merge(PL, ibov, how = 'inner', left_index=True, right_index=True)
consolido.head()


ajuste_cons = consolido/consolido.iloc[0]
ajuste_cons[['^BVSP', 'PL TOTAL']].plot(figsize=(7,5))

def simula_carteira(inicio , fim, carteira):
  precos = yf.download(list(carteira.keys()), start = inicio, end = fim, progress=False)
  primeiro = precos.iloc[0]
  compras_df = pd.Series(carteira, index=list(carteira.keys()))
  qtd_acoes = round(compras_df/primeiro['Close'])
  pl = precos['Close'] * qtd_acoes
  pl['PL TOTAL'] = pl.sum(axis=1)
  ibov = yf.download('^BVSP', start = inicio, end = fim, progress=False)['Close']
  consolido = pd.merge(pl, ibov, how = 'inner', left_index=True, right_index=True)
  ajuste_cons = consolido/consolido.iloc[0]
  ajuste_cons[['^BVSP', 'PL TOTAL']].plot(figsize=(7,5));
  return ajuste_cons

portifolio = {
    'ITSA4.SA': 500,  # Itaúsa
    'BBDC4.SA': 400,  # Bradesco
    'PETR3.SA': 600,  # Petrobras
    'VALE3.SA': 700,  # Vale
    'ABEV3.SA': 300,  # Ambev
    'ITUB4.SA': 550   # Itaú Unibanco
}

simula_carteira(inicio,fim ,portifolio)